### ISSUE TITLE
unclosed tags

### ISSUE THREAD

**Issue by amillet2001** [amillet2001/IPT2-CaseStudy#1]
hello everyone, please check your html files there are unclosed html tags detected

**Comment by NicholasDomingo** [comment]
okay, thanks for the heads up

**Comment by amillet2001** [comment]
common unclosed tags are the divs @NicholasDomingo please check your line 36 and 48

**Comment by BBautista001** [comment]
just checked mine, thanks for reminding

**Comment by CAPPasion** [comment]
I guess everything is all clear on this issue so far...

**Comment by NicholasDomingo** [comment]
updated those lines, thanks! @amillet2001

**Comment by CAPPasion** [comment]
also updated my lines on my branch, thanks for reminding...

**Comment by amillet2001** [comment]
thanks for settling the issues to your respective HTML files, i will now close this issue

**Comment by amillet2001** [comment]
Files are fixed, closing this issue now
