### ISSUE TITLE
unlinked css

### ISSUE THREAD

**Issue by NicholasDomingo** [amillet2001/IPT2-CaseStudy#2]
double check your link rel before uploading

**Comment by amillet2001** [comment]
links can also be broken if the css files are not within the html folder

**Comment by BBautista001** [comment]
thank you for the reminder

**Comment by CAPPasion** [comment]
my files are properly embedded on my side, thanks for reminding

**Comment by NicholasDomingo** [comment]
I hope everyone already have their unique designs in their website
