### ISSUE TITLE
add comments

### ISSUE THREAD

**Issue by BBautista001** [amillet2001/IPT2-CaseStudy#3]
add comments on your codes for others to understand which code does what

**Comment by amillet2001** [comment]
We decided to optionally upload the php files, I think I don't have to fix my branch

**Comment by CAPPasion** [comment]
On my side, I have decided to optionally upload a PHP file if needed, for now it's not needed. Thanks for reminding though.

**Comment by NicholasDomingo** [comment]
thanks for the reminder, haven't been able to handle PHP for a while, I've decided to opt out for now.

**Comment by BBautista001** [comment]
No problem guys. I guess I haven't got updated that PHP would be optional. Will be closing this issue now
