### ISSUE TITLE
pics folder uploaded

### ISSUE THREAD

**Issue by CAPPasion** [amillet2001/IPT2-CaseStudy#4]

**Comment by CAPPasion** [comment]
can everyone double-check their .jpeg and .png files if they are properly embedded to their respective HTML files?

**Comment by BBautista001** [comment]
just finished checking mine. So far, so good

**Comment by amillet2001** [comment]
I recently updated my picture, I feels like it's not professional like :3

**Comment by NicholasDomingo** [comment]
i just checked my file, so far so good

**Comment by CAPPasion** [comment]
I guess everything is clear, I'll close the issue.
